title: Alexander Wing # your name (or website title) here
logo: "images/circle.png?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Software Engineer, Delivery Officer @ Technocamps, Swansea University
  <br><br>
  Experience with languages such as Java, Python and swift. Feel free to contact me below:
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-wing-444262118/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
