title: Alexander Wing # your name (or website title) here
logo: "images/Alex Wing-crop.jpg?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Software Engineer, Delivery Officer @ Technocamps, Swansea University
  <br><br>
  Experience with numberous languages such as Java, Python and swift. My Most recent software development project: A swift iOS Ipad application used as a posture visualisation tool within Morriston Hospital, Swansea
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-wing-444262118/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
